# Generated by Django 6.0.5 on 2026-06-26 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_trat', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenUsuario',
        ),
        migrations.DeleteModel(
            name='ActividadFisica',
        ),
        migrations.DeleteModel(
            name='Alertas',
        ),
        migrations.DeleteModel(
            name='AnalisisGlucosa',
        ),
        migrations.DeleteModel(
            name='Comidas',
        ),
        migrations.DeleteModel(
            name='EstadoEmocional',
        ),
        migrations.DeleteModel(
            name='FeedbackPredicciones',
        ),
        migrations.DeleteModel(
            name='Glucosa',
        ),
        migrations.DeleteModel(
            name='Hba1C',
        ),
        migrations.DeleteModel(
            name='HistorialPeso',
        ),
        migrations.DeleteModel(
            name='Medicamentos',
        ),
        migrations.DeleteModel(
            name='Objetivos',
        ),
        migrations.DeleteModel(
            name='PatronesAprendidos',
        ),
        migrations.DeleteModel(
            name='RegistroComidas',
        ),
        migrations.DeleteModel(
            name='RegistroMedicamentos',
        ),
        migrations.DeleteModel(
            name='RegistroSueno',
        ),
        migrations.DeleteModel(
            name='ResumenDiario',
        ),
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
